-- Vunoh Global Database Schema + Sample Data
-- Generated by Django migrations
-- SQLite format

CREATE TABLE "assistant_task" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "task_code" varchar(20) NOT NULL UNIQUE, "original_request" text NOT NULL, "intent" varchar(50) NOT NULL, "entities" text NOT NULL CHECK ((JSON_VALID("entities") OR "entities" IS NULL)), "risk_score" integer NOT NULL, "risk_level" varchar(10) NOT NULL, "status" varchar(20) NOT NULL, "assigned_team" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);

CREATE TABLE "assistant_statushistory" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "old_status" varchar(20) NOT NULL, "new_status" varchar(20) NOT NULL, "changed_at" datetime NOT NULL, "task_id" bigint NOT NULL REFERENCES "assistant_task" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "assistant_taskmessage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "channel" varchar(20) NOT NULL, "subject" varchar(255) NOT NULL, "body" text NOT NULL, "created_at" datetime NOT NULL, "task_id" bigint NOT NULL REFERENCES "assistant_task" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "assistant_taskstep" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "step_number" integer NOT NULL, "description" text NOT NULL, "is_complete" bool NOT NULL, "task_id" bigint NOT NULL REFERENCES "assistant_task" ("id") DEFERRABLE INITIALLY DEFERRED);


-- Data for assistant_task
INSERT INTO assistant_task (id, task_code, original_request, intent, entities, risk_score, risk_level, status, assigned_team, created_at, updated_at) VALUES (1, 'VG-SEED0001', 'I need to send KES 15,000 to my mother in Kisumu urgently.', 'send_money', '{"amount": "15000", "currency": "KES", "recipient_name": "null", "recipient_relationship": "mother", "location": "Kisumu", "service_type": "null", "document_type": "null", "urgency": "high", "scheduled_date": "null", "notes": "null"}', 55, 'Medium', 'In Progress', 'Finance', 2026-05-11 11:59:45.828353, 2026-05-11 11:59:45.828420);
INSERT INTO assistant_task (id, task_code, original_request, intent, entities, risk_score, risk_level, status, assigned_team, created_at, updated_at) VALUES (2, 'VG-SEED0002', 'Please verify my land title deed for the plot in Karen.', 'verify_document', '{"amount": "null", "currency": "null", "recipient_name": "null", "recipient_relationship": "null", "location": "Karen", "service_type": "null", "document_type": "land_title", "urgency": "normal", "scheduled_date": "null", "notes": "null"}', 50, 'Medium', 'Pending', 'Legal', 2026-05-11 11:59:45.896473, 2026-05-11 11:59:45.896489);
INSERT INTO assistant_task (id, task_code, original_request, intent, entities, risk_score, risk_level, status, assigned_team, created_at, updated_at) VALUES (3, 'VG-SEED0003', 'Can someone clean my apartment in Westlands on Friday?', 'hire_service', '{"amount": "null", "currency": "null", "recipient_name": "null", "recipient_relationship": "null", "location": "Westlands", "service_type": "cleaner", "document_type": "null", "urgency": "normal", "scheduled_date": "Friday", "notes": "null"}', 10, 'Low', 'Completed', 'Operations', 2026-05-11 11:59:45.923565, 2026-05-11 11:59:45.923580);
INSERT INTO assistant_task (id, task_code, original_request, intent, entities, risk_score, risk_level, status, assigned_team, created_at, updated_at) VALUES (4, 'VG-SEED0004', 'I need a driver to pick up my father from JKIA tomorrow at 6am. He''s flying in from London.', 'get_airport_transfer', '{"amount": "null", "currency": "null", "recipient_name": "null", "recipient_relationship": "father", "location": "JKIA Nairobi", "service_type": "driver", "document_type": "null", "urgency": "high", "scheduled_date": "tomorrow 6am", "notes": "Arriving from London"}', 28, 'Low', 'In Progress', 'Logistics', 2026-05-11 11:59:45.956291, 2026-05-11 11:59:45.956306);
INSERT INTO assistant_task (id, task_code, original_request, intent, entities, risk_score, risk_level, status, assigned_team, created_at, updated_at) VALUES (5, 'VG-SEED0005', 'I need a lawyer to review a business partnership agreement in Nairobi CBD before I sign it.', 'hire_service', '{"amount": "null", "currency": "null", "recipient_name": "null", "recipient_relationship": "null", "location": "Nairobi CBD", "service_type": "lawyer", "document_type": "null", "urgency": "normal", "scheduled_date": "null", "notes": "Business partnership agreement review"}', 10, 'Low', 'Pending', 'Operations', 2026-05-11 11:59:45.987482, 2026-05-11 11:59:45.987500);

-- Data for assistant_taskstep
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (1, 1, 'Verify sender identity via KYC', False, 1);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (2, 2, 'Confirm recipient mobile money account', False, 1);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (3, 3, 'Process KES 15,000 transfer via M-Pesa', False, 1);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (4, 4, 'Send confirmation SMS to both parties', False, 1);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (5, 5, 'Log transaction for audit trail', False, 1);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (6, 1, 'Receive scanned land title document', False, 2);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (7, 2, 'Cross-reference with Ministry of Lands registry', False, 2);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (8, 3, 'Conduct encumbrance and lien search', False, 2);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (9, 4, 'Confirm authenticity with legal expert', False, 2);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (10, 5, 'Issue verification certificate', False, 2);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (11, 1, 'Match with vetted cleaning service provider in Westlands', False, 3);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (12, 2, 'Confirm Friday availability and schedule', False, 3);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (13, 3, 'Share property access instructions securely', False, 3);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (14, 4, 'Complete cleaning service', False, 3);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (15, 5, 'Collect customer sign-off and rating', False, 3);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (16, 1, 'Confirm flight arrival details for London inbound', False, 4);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (17, 2, 'Assign vetted driver for JKIA pickup at 6am', False, 4);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (18, 3, 'Share driver contact and vehicle details with customer', False, 4);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (19, 4, 'Driver meets passenger at arrivals', False, 4);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (20, 5, 'Confirm safe drop-off and close task', False, 4);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (21, 1, 'Match customer with qualified business lawyer in Nairobi CBD', False, 5);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (22, 2, 'Securely receive the partnership agreement document', False, 5);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (23, 3, 'Lawyer reviews terms, liabilities, and red flags', False, 5);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (24, 4, 'Provide written legal opinion and recommendations', False, 5);
INSERT INTO assistant_taskstep (id, step_number, description, is_complete, task_id) VALUES (25, 5, 'Customer confirms review and proceeds with signing decision', False, 5);

-- Data for assistant_taskmessage
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (1, 'whatsapp', '', 'Hi there 👋

Your task has been created!

*Task Code:* VG-SEED0001
*Service:* Send Money — KES 15,000 to mother in Kisumu
*Status:* Pending

Our Finance team will process this shortly. We''ll keep you updated! 🇰🇪', 2026-05-11 11:59:45.884351, 1);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (2, 'email', 'Task Confirmation — VG-SEED0001 | Money Transfer', 'Dear Valued Customer,

Thank you for using Vunoh Global. Your request has been received and assigned to our Finance Team.

Task Code: VG-SEED0001
Service: Send Money
Amount: KES 15,000
Recipient: Mother (Kisumu)
Urgency: High
Status: Pending

We will process your transfer and confirm once complete.

Kind regards,
Vunoh Global Support Team', 2026-05-11 11:59:45.887397, 1);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (3, 'sms', '', 'VUNOH: Task VG-SEED0001 created. KES 15,000 transfer to Kisumu. Finance Team assigned. Ref: VG-SEED0001', 2026-05-11 11:59:45.890418, 1);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (4, 'whatsapp', '', 'Hello! 📄

Task *VG-SEED0002* has been created.
*Service:* Land Title Verification — Karen
*Team:* Legal
*Status:* Pending

Our Legal team will begin verification shortly.', 2026-05-11 11:59:45.914625, 2);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (5, 'email', 'Task Confirmation — VG-SEED0002 | Land Title Verification', 'Dear Valued Customer,

Your document verification request has been received.

Task Code: VG-SEED0002
Service: Verify Document
Document Type: Land Title Deed
Location: Karen
Assigned Team: Legal
Status: Pending

Our legal team will verify authenticity via the Kenya Lands Registry.

Kind regards,
Vunoh Global Legal Team', 2026-05-11 11:59:45.917428, 2);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (6, 'sms', '', 'VUNOH: Task VG-SEED0002 created. Land title verification Karen. Legal Team assigned. Ref: VG-SEED0002', 2026-05-11 11:59:45.920574, 2);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (7, 'whatsapp', '', 'Hi! 🧹

Task *VG-SEED0003* created!
*Service:* Cleaning — Westlands apartment
*Scheduled:* Friday
*Team:* Operations

We''ll match you with a vetted cleaner shortly.', 2026-05-11 11:59:45.942015, 3);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (8, 'email', 'Task Confirmation — VG-SEED0003 | Cleaning Service', 'Dear Valued Customer,

Your service hire request has been received.

Task Code: VG-SEED0003
Service: Hire Cleaner
Location: Westlands
Scheduled: Friday
Assigned Team: Operations
Status: Pending

We will match you with a vetted cleaning professional.

Kind regards,
Vunoh Global Operations Team', 2026-05-11 11:59:45.945119, 3);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (9, 'sms', '', 'VUNOH: Task VG-SEED0003 created. Cleaner Westlands on Friday. Operations Team assigned. Ref: VG-SEED0003', 2026-05-11 11:59:45.948232, 3);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (10, 'whatsapp', '', 'Got it! 🚗

Task *VG-SEED0004* created.
*Service:* Airport Transfer — JKIA pickup
*Time:* Tomorrow 6am
*Team:* Logistics

We''ll assign a driver and send details shortly.', 2026-05-11 11:59:45.974680, 4);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (11, 'email', 'Task Confirmation — VG-SEED0004 | Airport Transfer', 'Dear Valued Customer,

Your airport transfer request has been received.

Task Code: VG-SEED0004
Service: Airport Transfer
Pickup: JKIA, Tomorrow at 6:00 AM
Passenger: Father (arriving from London)
Assigned Team: Logistics
Urgency: High
Status: Pending

A driver will be assigned and details shared with you shortly.

Kind regards,
Vunoh Global Logistics Team', 2026-05-11 11:59:45.977649, 4);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (12, 'sms', '', 'VUNOH: Task VG-SEED0004 created. JKIA pickup tomorrow 6am. Logistics Team assigned. Ref: VG-SEED0004', 2026-05-11 11:59:45.980846, 4);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (13, 'whatsapp', '', 'Hello! ⚖️

Task *VG-SEED0005* created.
*Service:* Legal Review — Partnership Agreement
*Location:* Nairobi CBD
*Team:* Operations

Our team will connect you with a qualified lawyer.', 2026-05-11 11:59:46.006960, 5);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (14, 'email', 'Task Confirmation — VG-SEED0005 | Legal Service', 'Dear Valued Customer,

Your request for a legal professional has been received.

Task Code: VG-SEED0005
Service: Hire Lawyer
Purpose: Business Partnership Agreement Review
Location: Nairobi CBD
Assigned Team: Operations
Status: Pending

A qualified lawyer will be assigned to review your agreement.

Kind regards,
Vunoh Global Operations Team', 2026-05-11 11:59:46.010114, 5);
INSERT INTO assistant_taskmessage (id, channel, subject, body, created_at, task_id) VALUES (15, 'sms', '', 'VUNOH: Task VG-SEED0005 created. Lawyer review partnership agreement Nairobi CBD. Operations Team. Ref: VG-SEED0005', 2026-05-11 11:59:46.013094, 5);

-- Data for assistant_statushistory
INSERT INTO assistant_statushistory (id, old_status, new_status, changed_at, task_id) VALUES (1, 'Pending', 'In Progress', 2026-05-11 11:59:45.893435, 1);
INSERT INTO assistant_statushistory (id, old_status, new_status, changed_at, task_id) VALUES (2, 'Pending', 'Completed', 2026-05-11 11:59:45.951187, 3);
INSERT INTO assistant_statushistory (id, old_status, new_status, changed_at, task_id) VALUES (3, 'Pending', 'In Progress', 2026-05-11 11:59:45.983996, 4);
